### ISSUE TITLE
Twisted 19.2.0 breaking with scrapy

### ISSUE THREAD

**Issue by patalanov** [vimagick/dockerfiles#104]
According to this issue: (https://github.com/scrapy/scrapyd/issues/311), **Twisted 19.2.0 assumes http headers are of string type**, scrapyd as well as scrapyrt are currently breaking if Twisted version is `19.2.0`, and it must be downgraded to `18.9.1` in order to fix the issue.

with this set up in a docker container service:

```
    #~  if using scrapyrt ~
    #pass spider to requests parameters # 
    params = {
            'spider_name': spider,
            'start_requests':True
            }
    # scrape items
    response = requests.get('http://scrapyrt:9080/crawl.json', params)
    data = response.json()
```

no crawling response can be parsed.

Could you guys please check on this? your image is breaking on my docker project, built like so:

```
  scrapyrt:
    image: vimagick/scrapyd:py3
    command: scrapyrt -i 0.0.0.0 -p 9080
    restart: always
    ports:
      - '9080:9080'
    volumes:
      - ./services/web:/usr/src/app
    working_dir: /usr/src/app/project/api
    depends_on:
      - web
    links: 
      - web
```

Full Traceback:

```
scrapyrt_1         | 2019-05-21 17:27:18+0000 [-] Log opened.
scrapyrt_1         | 2019-05-21 17:27:18+0000 [-] Site starting on 9080
scrapyrt_1         | 2019-05-21 17:27:18+0000 [-] Starting factory <twisted.web.server.Site object at 0x7ff105d31b38>
scrapyrt_1         | 2019-05-21 17:28:29+0000 [-] Received SIGTERM, shutting down.
scrapyrt_1         | 2019-05-21 17:28:29+0000 [-] (TCP Port 9080 Closed)
scrapyrt_1         | 2019-05-21 17:28:29+0000 [-] Stopping factory <twisted.web.server.Site object at 0x7ff105d31b38>
scrapyrt_1         | 2019-05-21 17:28:29+0000 [-] Main loop terminated.
scrapyrt_1         | 2019-05-21 17:29:14+0000 [-] Log opened.
scrapyrt_1         | 2019-05-21 17:29:14+0000 [-] Site starting on 9080
scrapyrt_1         | 2019-05-21 17:29:15+0000 [-] Starting factory <twisted.web.server.Site object at 0x7f3ee6a38b38>
scrapyrt_1         | 2019-05-21 17:35:43+0000 [-] Received SIGTERM, shutting down.
scrapyrt_1         | 2019-05-21 17:35:43+0000 [-] (TCP Port 9080 Closed)
scrapyrt_1         | 2019-05-21 17:35:43+0000 [-] Stopping factory <twisted.web.server.Site object at 0x7f3ee6a38b38>
scrapyrt_1         | 2019-05-21 17:35:43+0000 [-] Main loop terminated.
scrapyrt_1         | 2019-05-21 17:35:46+0000 [-] Unhandled error in Deferred:
scrapyrt_1         | Unhandled error in Deferred:
scrapyrt_1         | 2019-05-21 17:35:46+0000 [-] Unhandled Error
scrapyrt_1         | 	Traceback (most recent call last):
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
scrapyrt_1         | 	    _inlineCallbacks(r, g, status)
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1421, in _inlineCallbacks
scrapyrt_1         | 	    status.deferred.callback(getattr(e, "value", None))
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 460, in callback
scrapyrt_1         | 	    self._startRunCallbacks(result)
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
scrapyrt_1         | 	    self._runCallbacks()
scrapyrt_1         | 	--- <exception caught here> ---
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
scrapyrt_1         | 	    current.result = callback(current.result, *args, **kw)
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/scrapyrt/resources.py", line 37, in finish_request
scrapyrt_1         | 	    request.write(self.render_object(obj, request))
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/scrapyrt/resources.py", line 95, in render_object
scrapyrt_1         | 	    request.setHeader('Content-Length', len(r))
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1271, in setHeader
scrapyrt_1         | 	    self.responseHeaders.setRawHeaders(name, [value])
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 220, in setRawHeaders
scrapyrt_1         | 	    for v in self._encodeValues(values)]
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 220, in <listcomp>
scrapyrt_1         | 	    for v in self._encodeValues(values)]
scrapyrt_1         | 	  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
scrapyrt_1         | 	    return b' '.join(headerComponent.splitlines())
scrapyrt_1         | 	builtins.AttributeError: 'int' object has no attribute 'splitlines'
scrapyrt_1         | 	
scrapyrt_1         | 
scrapyrt_1         | Traceback (most recent call last):
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
scrapyrt_1         |     result = g.send(result)
scrapyrt_1         | StopIteration
scrapyrt_1         | 
scrapyrt_1         | During handling of the above exception, another exception occurred:
scrapyrt_1         | 
scrapyrt_1         | Traceback (most recent call last):
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
scrapyrt_1         |     result = g.send(result)
scrapyrt_1         | StopIteration
scrapyrt_1         | 
scrapyrt_1         | During handling of the above exception, another exception occurred:
scrapyrt_1         | 
scrapyrt_1         | Traceback (most recent call last):
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
scrapyrt_1         |     result = g.send(result)
scrapyrt_1         | StopIteration
scrapyrt_1         | 
scrapyrt_1         | During handling of the above exception, another exception occurred:
scrapyrt_1         | 
scrapyrt_1         | Traceback (most recent call last):
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
scrapyrt_1         |     current.result = callback(current.result, *args, **kw)
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/scrapyrt/resources.py", line 37, in finish_request
scrapyrt_1         |     request.write(self.render_object(obj, request))
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/scrapyrt/resources.py", line 95, in render_object
scrapyrt_1         |     request.setHeader('Content-Length', len(r))
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1271, in setHeader
scrapyrt_1         |     self.responseHeaders.setRawHeaders(name, [value])
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 220, in setRawHeaders
scrapyrt_1         |     for v in self._encodeValues(values)]
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 220, in <listcomp>
scrapyrt_1         |     for v in self._encodeValues(values)]
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
scrapyrt_1         |     return b' '.join(headerComponent.splitlines())
scrapyrt_1         | AttributeError: 'int' object has no attribute 'splitlines'
```

**Comment by vimagick** [comment]
It was fixed: https://github.com/scrapy/scrapyd/issues/311 😄
