### ISSUE TITLE
youtube-dl missing 'AtomicParsley ' when using --embed-thumbnail

### ISSUE THREAD

**Issue by jobrien2001** [vimagick/dockerfiles#115]
when using switch --embed-thumbnail this error pops up

```
ERROR: AtomicParsley was not found. Please install.

Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2054, in post_process
files_to_delete, info = pp.run(info)
File "/usr/lib/python3.7/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 60, in run
raise EmbedThumbnailPPError('AtomicParsley was not found. Please install.')
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: AtomicParsley was not found. Please install.
```

**Comment by PiotrBalik** [comment]
Download `AtomicParsley` from https://github.com/wez/atomicparsley and add to path

**Comment by AustinSaintAubin** [comment]
What path does AtomicParsley need to be installed to?

**Comment by PiotrBalik** [comment]
Any system path that makes it visible from your console, so that `youtube-dl` can also use it.
Check out [https://askubuntu.com/questions/109381/how-to-add-path-of-a-program-to-path-environment-variable](https://askubuntu.com/questions/109381/how-to-add-path-of-a-program-to-path-environment-variable)

**Comment by AustinSaintAubin** [comment]
Ah, thanks.
