### ISSUE TITLE
Error running scrapyd-deploy with this image

### ISSUE THREAD

**Issue by sneldev** [vimagick/dockerfiles#151]
After a docker file buid and bashing to the container, I always get this error if launching scrapyd-deploy

root@eca5e14b9eda:~# scrapyd-deploy
Traceback (most recent call last):
  File "/usr/local/bin/scrapyd-deploy", line 5, in <module>
    from scrapyd_client.deploy import main
  File "/usr/local/lib/python3.7/dist-packages/scrapyd_client/deploy.py", line 20, in <module>
    import setuptools  # noqa: F401 not used in code but needed in runtime, don't remove!
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils.core'

**Comment by sneldev** [comment]
image is "scrapyd"

**Comment by sneldev** [comment]
error on my side
