### ISSUE TITLE
urlwatch - module xmpp reporter missing

### ISSUE THREAD

**Issue by chriswegit** [vimagick/dockerfiles#195]
Hi,
I'm currently switching my urlwatch-instance from a "regular" install to docker.
On my old setup I'm using the xmpp-reporter to get notified about URL-changes.
On the docker instance I added the same xmpp credentials to my urlwatch.yaml but didn't get notifications - so I checked "urlwatch --test-reporter xmpp" and got the following output:

```
bash-5.1# urlwatch --test-reporter xmpp
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/urlwatch/cli.py", line 112, in main
    urlwatch_command.run()
  File "/usr/lib/python3.9/site-packages/urlwatch/command.py", line 407, in run
    self.check_test_reporter()
  File "/usr/lib/python3.9/site-packages/urlwatch/command.py", line 313, in check_test_reporter
    report.finish_one(name)
  File "/usr/lib/python3.9/site-packages/urlwatch/handler.py", line 218, in finish_one
    ReporterBase.submit_one(name, self, self.job_states, duration)
  File "/usr/lib/python3.9/site-packages/urlwatch/reporters.py", line 124, in submit_one
    subclass(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3.9/site-packages/urlwatch/reporters.py", line 995, in submit
    xmpp = XMPP(sender, recipient, self.config.get('insecure_password'))
  File "/usr/lib/python3.9/site-packages/urlwatch/xmpp.py", line 47, in __init__
    raise ImportError('Python module "aioxmpp" not installed')
ImportError: Python module "aioxmpp" not installed
```

Is it possible to implement the missing module in the image?

Thanks and best regards,
chris

**Comment by chriswegit** [comment]
Perfect! works fine now - thank you
