### ISSUE TITLE
module xmpp reporter not installed

### ISSUE THREAD

**Issue by chriswegit** [vimagick/dockerfiles#205]
Hi, 
I noticed that the xmpp-reporter is not working again - probably it's the same line missing like in issue#195
as a result of a python update?

output of --test-reporter xmpp:
`urlwatch:~/.urlwatch# urlwatch --test-reporter xmpp
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/urlwatch/cli.py", line 112, in main
    urlwatch_command.run()
  File "/usr/lib/python3.10/site-packages/urlwatch/command.py", line 457, in run
    self.check_test_reporter()
  File "/usr/lib/python3.10/site-packages/urlwatch/command.py", line 363, in check_test_reporter
    report.finish_one(name)
  File "/usr/lib/python3.10/site-packages/urlwatch/handler.py", line 223, in finish_one
    ReporterBase.submit_one(name, self, self.job_states, duration)
  File "/usr/lib/python3.10/site-packages/urlwatch/reporters.py", line 129, in submit_one
    subclass(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3.10/site-packages/urlwatch/reporters.py", line 1033, in submit
    xmpp = XMPP(sender, recipient, self.config.get('insecure_password'))
  File "/usr/lib/python3.10/site-packages/urlwatch/xmpp.py", line 47, in __init__
    raise ImportError('Python module "aioxmpp" not installed')
ImportError: Python module "aioxmpp" not installed`

best regards,
chris

**Comment by vimagick** [comment]
Hi

What version are you using?
You can get the latest image [here](https://github.com/EasyPi/docker-urlwatch)

**Comment by chriswegit** [comment]
Hi,
updated to latest version - works fine again.
many thanks,
chris
