### ISSUE TITLE
youtube-dl: Modify docker-run command

### ISSUE THREAD

**Issue by marvinwankersteen** [vimagick/dockerfiles#45]
Hi,

if I use ur docker-run command then I get a warning that the cache-folder is not writeable:

`WARNING: Writing cache to '/.cache/youtube-dl/youtube-sigfuncs/js_vfl4Xq3l4_43.40.json' failed: Traceback (most recent call last):`

I use this alias:
`alias youtube-dl='docker run --rm -u $(id -u):$(id -g) -v $PWD:/data vimagick/youtube-dl --cache-dir /tmp'`

**Comment by kenorb** [comment]
Same here.

I'm following the tutorial at [hub.docker.com](https://hub.docker.com/r/vimagick/youtube-dl/). So:

```
$ alias yt='docker run --rm -u $(id -u):$(id -g) -v $PWD:/data vimagick/youtube-dl'
$ yt -F nVjsGKrE6E8
...
[youtube] nVjsGKrE6E8: Downloading js player vfl9zpg5e
WARNING: Writing cache to '/.cache/youtube-dl/youtube-sigfuncs/js_vfl9zpg5e_40.41.json' failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/cache.py", line 49, in store
    os.makedirs(os.path.dirname(fn))
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
...
```
